#!/usr/bin/env bash
# Tenxo Edge Agent — one-command install for GPU providers.
# Usage:
#   curl -fsSL https://tenxo-api.onrender.com/install.sh | bash -s -- --owner YOUR_USER_ID
set -euo pipefail

RELEASE_URL="https://github.com/Tanya25-05/tenxo/releases/download/v.0.1.0/edge_agent-linux-amd64"
BIN_DIR="/usr/local/bin"
CONFIG_DIR="/etc/tenxo"
SERVICE_NAME="tenxo-agent"
MATCHMAKER_URL="${MATCHMAKER_URL:-https://tenxo-api.onrender.com}"
REPO_URL="https://github.com/Tanya25-05/tenxo.git"

echo "============================================"
echo " Tenxo Edge Agent Installer"
echo "============================================"

# ── Parse args ────────────────────────────────────────────────────────────
OWNER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --owner) OWNER="$2"; shift 2 ;;
    --matchmaker-url) MATCHMAKER_URL="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

if [ -z "$OWNER" ]; then
  echo ""
  echo "ERROR: You must provide your user ID."
  echo ""
  echo "  curl -fsSL https://tenxo-api.onrender.com/install.sh | bash -s -- --owner YOUR_USER_ID"
  echo ""
  echo "Find your user ID in the Tenxo dashboard:"
  echo "  1. Sign in at https://tenxo.onrender.com"
  echo "  2. Go to Provider Console"
  echo "  3. Copy your User ID from the top of the page"
  echo ""
  exit 1
fi

# ── Prerequisites ──────────────────────────────────────────────────────────
command -v docker &>/dev/null || {
  echo "ERROR: Docker is required. Install: https://docs.docker.com/engine/install/"
  exit 1
}

command -v cargo &>/dev/null || {
  echo "ERROR: Rust/Cargo is required. Install:"
  echo "  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
  exit 1
}

if ! command -v cryptsetup &>/dev/null || ! command -v mkfs.ext4 &>/dev/null; then
  if command -v apt-get &>/dev/null; then
    echo "Installing LUKS workspace dependencies..."
    sudo apt-get update
    sudo apt-get install -y cryptsetup e2fsprogs util-linux
  else
    echo "ERROR: cryptsetup, mkfs.ext4, mount, umount, and shred are required for LUKS workspaces."
    echo "Install cryptsetup/e2fsprogs/util-linux with your OS package manager and rerun this installer."
    exit 1
  fi
fi

# ── Clone edge_agent only (sparse checkout) ────────────────────────────────
BUILD_DIR="/tmp/tenxo-build"
echo "[1/4] Building edge agent from source..."
rm -rf "$BUILD_DIR"
git clone --depth 1 --filter=blob:none --sparse "$REPO_URL" "$BUILD_DIR" 2>/dev/null || {
  echo "ERROR: Failed to clone repository. Check your internet connection."
  exit 1
}
cd "$BUILD_DIR"
git sparse-checkout set edge_agent
cd edge_agent
cargo build --release 2>&1 | tail -5
echo "       Build complete"

# ── Install binary ─────────────────────────────────────────────────────────
echo "[2/4] Installing binary..."
sudo mkdir -p "$BIN_DIR"
sudo cp "$BUILD_DIR/edge_agent/target/release/edge_agent" "$BIN_DIR/edge_agent"
sudo chmod +x "$BIN_DIR/edge_agent"
rm -rf "$BUILD_DIR"
echo "       Installed $BIN_DIR/edge_agent"

# ── Create config ──────────────────────────────────────────────────────────
echo "[3/4] Configuring..."
sudo mkdir -p "$CONFIG_DIR"
cat << ENVEOF | sudo tee "$CONFIG_DIR/agent.env" > /dev/null
# Tenxo Edge Agent Configuration
# Auto-generated by install.sh

# Matchmaker connection (WebSocket bridge on port 8080)
MATCHMAKER_URL=https://tenxo-api.onrender.com

# Your account ID (from the Tenxo dashboard)
OWNER=$OWNER

# Optional: custom node ID (defaults to hostname)
# NODE_ID=

# Docker-visible job workspace root. Do not use /tmp with PrivateTmp=true.
TENXO_WORK_DIR=/var/lib/tenxo/workspaces
ENVEOF
echo "       Created $CONFIG_DIR/agent.env"
sudo mkdir -p /var/lib/tenxo/workspaces

# ── Install systemd service ────────────────────────────────────────────────
echo "[4/4] Installing systemd service..."
cat << UNITEOF | sudo tee "/etc/systemd/system/$SERVICE_NAME.service" > /dev/null
[Unit]
Description=Tenxo GPU Edge Agent
Documentation=https://tenxo-api.onrender.com/docs
After=network-online.target docker.service
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=/etc/tenxo/agent.env
ExecStart=/usr/local/bin/edge_agent
Restart=always
RestartSec=10
LimitNOFILE=65536

# Security hardening
NoNewPrivileges=true
ProtectSystem=full
ProtectHome=true
PrivateTmp=true
ReadWritePaths=/var/lib/tenxo

[Install]
WantedBy=multi-user.target
UNITEOF

sudo systemctl daemon-reload
sudo systemctl enable "$SERVICE_NAME"
sudo systemctl restart "$SERVICE_NAME"
echo "       $SERVICE_NAME service installed and started"

# ── Verify ─────────────────────────────────────────────────────────────────
echo ""
sleep 2
if systemctl is-active --quiet "$SERVICE_NAME"; then
  echo ""
  echo "============================================"
  echo " Tenxo Edge Agent is RUNNING"
  echo "============================================"
  echo ""
  echo "  Check status:  sudo systemctl status $SERVICE_NAME"
  echo "  View logs:     sudo journalctl -u $SERVICE_NAME -f"
  echo "  Config:        $CONFIG_DIR/agent.env"
  echo ""
  echo "  Your GPU should appear in the dashboard"
  echo "  within 30 seconds."
else
  echo "ERROR: Service failed to start."
  echo "  Check: sudo journalctl -u $SERVICE_NAME -n 50"
  exit 1
fi
