#!/usr/bin/env bash
# Tenxo Edge Agent — one-command install for GPU providers.
# Usage:
#   curl -fsSL https://tenxo-api.onrender.com/install.sh | bash -s -- --owner YOUR_USER_ID
set -euo pipefail

RELEASE_URL="https://github.com/Shailendra1703/tenxo-release/releases/download/latest/edge_agent-linux-amd64"
BIN_DIR="/usr/local/bin"
CONFIG_DIR="/etc/tenxo"
SERVICE_NAME="tenxo-agent"
MATCHMAKER_URL="${MATCHMAKER_URL:-https://tenxo-api.onrender.com}"
REPO_URL="https://github.com/Tanya25-05/tenxo.git"

echo "============================================"
echo " Tenxo Edge Agent Installer"
echo "============================================"

# ── Parse args ────────────────────────────────────────────────────────────
OWNER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --owner) OWNER="$2"; shift 2 ;;
    --matchmaker-url) MATCHMAKER_URL="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

if [ -z "$OWNER" ]; then
  echo ""
  echo "ERROR: You must provide your user ID."
  echo ""
  echo "  curl -fsSL https://tenxo-api.onrender.com/install.sh | bash -s -- --owner YOUR_USER_ID"
  echo ""
  echo "Find your user ID in the Tenxo dashboard:"
  echo "  1. Sign in at https://tenxo.onrender.com"
  echo "  2. Go to Provider Console"
  echo "  3. Copy your User ID from the top of the page"
  echo ""
  exit 1
fi

# ── Prerequisites ──────────────────────────────────────────────────────────
command -v docker &>/dev/null || {
  echo "ERROR: Docker is required. Install: https://docs.docker.com/engine/install/"
  exit 1
}

# Need a downloader to fetch the prebuilt release binary
if ! command -v curl &>/dev/null && ! command -v wget &>/dev/null; then
  echo "ERROR: curl or wget is required to download the release binary."
  exit 1
fi

# ── Get prebuilt binary from release URL ────────────────────────────────────
echo "[1/4] Downloading edge agent release..."
TMP_BIN="$(mktemp)"
if command -v curl &>/dev/null; then
  curl -fsSL "$RELEASE_URL" -o "$TMP_BIN" || {
    echo "ERROR: Failed to download release from $RELEASE_URL"
    rm -f "$TMP_BIN"
    exit 1
  }
else
  wget -qO "$TMP_BIN" "$RELEASE_URL" || {
    echo "ERROR: Failed to download release from $RELEASE_URL"
    rm -f "$TMP_BIN"
    exit 1
  }
fi
chmod +x "$TMP_BIN"
echo "       Download complete"

# ── Install binary ─────────────────────────────────────────────────────────
echo "[2/4] Installing binary..."
sudo mkdir -p "$BIN_DIR"
sudo install -m 0755 "$TMP_BIN" "$BIN_DIR/edge_agent"
rm -f "$TMP_BIN"
echo "       Installed $BIN_DIR/edge_agent"

# ── Create config ──────────────────────────────────────────────────────────
echo "[3/4] Configuring..."
sudo mkdir -p "$CONFIG_DIR"
cat << ENVEOF | sudo tee "$CONFIG_DIR/agent.env" > /dev/null
# Tenxo Edge Agent Configuration
# Auto-generated by install.sh

# Matchmaker connection
NATS_URL=nats://tenxo-api.onrender.com:4222
MATCHMAKER_URL=https://tenxo-api.onrender.com

# Your account ID (from the Tenxo dashboard)
OWNER=$OWNER

# Optional: custom node ID (defaults to hostname)
# NODE_ID=
ENVEOF
echo "       Created $CONFIG_DIR/agent.env"

# ── Install systemd service ────────────────────────────────────────────────
echo "[4/4] Installing systemd service..."
cat << UNITEOF | sudo tee "/etc/systemd/system/$SERVICE_NAME.service" > /dev/null
[Unit]
Description=Tenxo GPU Edge Agent
Documentation=https://tenxo-api.onrender.com/docs
After=network-online.target docker.service
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=/etc/tenxo/agent.env
ExecStart=/usr/local/bin/edge_agent
Restart=always
RestartSec=10
LimitNOFILE=65536

# Security hardening
NoNewPrivileges=true
ProtectSystem=full
ProtectHome=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
UNITEOF

sudo systemctl daemon-reload
sudo systemctl enable "$SERVICE_NAME"
sudo systemctl restart "$SERVICE_NAME"
echo "       $SERVICE_NAME service installed and started"

# ── Verify ─────────────────────────────────────────────────────────────────
echo ""
sleep 2
if systemctl is-active --quiet "$SERVICE_NAME"; then
  echo ""
  echo "============================================"
  echo " Tenxo Edge Agent is RUNNING"
  echo "============================================"
  echo ""
  echo "  Check status:  sudo systemctl status $SERVICE_NAME"
  echo "  View logs:     sudo journalctl -u $SERVICE_NAME -f"
  echo "  Config:        $CONFIG_DIR/agent.env"
  echo ""
  echo "  Your GPU should appear in the dashboard"
  echo "  within 30 seconds."
else
  echo "ERROR: Service failed to start."
  echo "  Check: sudo journalctl -u $SERVICE_NAME -n 50"
  exit 1
fi
